[project]
name = "vadim-clicker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keyboard>=0.13.5",
    "kivy>=2.3.1",
    "mouse>=0.7.1",
    "nuitka>=2.8.9",
    "prettytable>=3.17.0",
]
